# Generated by Django 4.2 on 2025-08-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_contactinfo_alter_message_sender_message_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='token_number',
            field=models.CharField(blank=True, db_index=True, max_length=24, unique=True),
        ),
    ]
