# Generated by Django 4.2 on 2025-08-23 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_contactinfo_token_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='token_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.contactinfo'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', 'User'), ('bot', 'Bot'), ('admin', 'Admin'), ('system', 'System')], default='user', max_length=20),
        ),
    ]
