# Generated by Django 4.2 on 2025-08-25 05:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_contactinfo_session_key_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='contact_value',
            field=models.CharField(blank=True, help_text='Primary identifier (phone/email/both/temp)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, help_text='Django session key', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='token_number',
            field=models.CharField(blank=True, db_index=True, help_text='Unique token for each session/user', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(choices=[('user', '🧑 User'), ('bot', '🤖 Bot'), ('admin', '🛠 Admin'), ('system', '⚙ System')], default='user', max_length=20),
        ),
    ]
