# Generated by Django 4.2 on 2025-08-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_pageview_visitorlog_chatsentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsentiment',
            name='message',
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
        migrations.DeleteModel(
            name='VisitorLog',
        ),
        migrations.DeleteModel(
            name='ChatSentiment',
        ),
    ]
