# Generated by Django 4.2 on 2025-08-28 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_remove_chatsentiment_message_delete_pageview_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'ordering': ['-last_active'], 'verbose_name': 'Contact Info', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterIndexTogether(
            name='message',
            index_together={('contact', 'timestamp')},
        ),
    ]
