# Generated by Django 4.2 on 2025-08-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinfo',
            options={},
        ),
        migrations.AlterIndexTogether(
            name='message',
            index_together=set(),
        ),
    ]
