# Generated by Django 4.2 on 2025-09-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_contactinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='referrer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
