# Generated by Django 4.2 on 2025-09-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_contactinfo_referrer_contactinfo_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='page_views',
            field=models.PositiveIntegerField(default=0, help_text='Number of pages visited'),
        ),
    ]
