# Generated by Django 4.2 on 2025-09-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_contactinfo_page_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='location_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='location_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='location_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
